CREATE SCHEMA `SIS2402`; -- Criando DB

USE `SIS2402`; -- SELECIONANDO DB PARA USO

CREATE TABLE `SIS2402`.`CLIENTES`( -- Criando tabela "CLIENTES" na DB "SIS2402"
	`ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
	`NOME` MEDIUMTEXT NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `NASCIMENTO` DATE NOT NULL,
    `GENERO` VARCHAR(9) NOT NULL,
    `CEP` INT NOT NULL,
    `RUA` LONGTEXT NOT NULL,
    `NUMERO` INT NOT NULL,
    `BAIRRO` TEXT NOT NULL,
    `CIDADE` MEDIUMTEXT NOT NULL,
    `UF` VARCHAR(2) NOT NULL,
    `PAIS` TEXT NOT NULL,    
	PRIMARY KEY(`ID_CLIENTE`)
);

-- INSERINDO DADOS NA TABELA
INSERT INTO `SIS2402`.`CLIENTES` (`NOME`, `EMAIL`, `NASCIMENTO`, `GENERO`, `CEP`, `RUA`, `NUMERO`, `BAIRRO`, `CIDADE`, `UF`, `PAIS`)
VALUES('Alex', 'alex@email.com', '1991-01-01', 'masculino', 80500700, 'Rua do Joaquim', 1337, 'Santo', 'Videira', 'SC', 'Brasil');

-- EXIBINDO/CONSULTANDO DADOS
SELECT * FROM `SIS2402`.`CLIENTES`;