-- CRIAR UM NOVO BD
CREATE DATABASE GREENHOUSE;

-- UTILIZANDO O BD
USE GREENHOUSE;

-- CRIANDO UMA TABELA
CREATE TABLE `GREENHOUSE`.`PLANTS`(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL
		DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DML DE INSERÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Orquídea', 10, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Samambaia', 11, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Babosa', 9, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Palmeira', 15, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Coqueiro', 20, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Pinheiro', 25, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Cânhamo', 420, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Girassol', 2, 'LOW');

-- 
INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Violeta', 666, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES ('Mandioca', 51, 'LOW');

-- EXECUTANDO COMANDOS DQL - SELECT
-- Consultando tudo da tabela
SELECT * FROM GREENHOUSE.PLANTS;

-- Especificando apenas as colunas desejadas
SELECT PLANT_NAME, SENSOR_EVENT FROM PLANTS;

-- Aplicar filtros nos registros de dados
SELECT * FROM PLANTS WHERE SENSOR_LEVEL = 'HIGH';
-- Múltiplos filtros
SELECT * FROM PLANTS WHERE SENSOR_LEVEL = 'HIGH' AND SENSOR_VALUE >= 10 AND SENSOR_VALUE <= 20;
-- Mais técnicas de filtro
SELECT * FROM PLANTS WHERE SENSOR_LEVEL IN ('HIGH', 'LOW');
-- Cláusula de ordenação
SELECT * FROM PLANTS WHERE SENSOR_VALUE < 420 ORDER BY SENSOR_VALUE DESC;
-- Funções de agrupamento
SELECT COUNT(*), SENSOR_LEVEL FROM PLANTS GROUP BY SENSOR_LEVEL; -- COUNT / MAX / AVERAGE / MIN
-- ----------------------------------------------------------------------------------------------
SELECT SENSOR_VALUE FROM PLANTS WHERE SENSOR_VALUE < 52 ORDER BY SENSOR_VALUE DESC LIMIT 3;
-- MAX
SELECT MAX(SENSOR_VALUE), MIN(SENSOR_VALUE) FROM PLANTS WHERE LENGTH(PLANT_NAME) > 3;
-- COUNT
SELECT COUNT(SENSOR_VALUE)
FROM PLANTS WHERE SENSOR_VALUE > 10;
-- SUM
SELECT SUM(SENSOR_VALUE) FROM PLANTS WHERE SENSOR_VALUE > 100;
-- AVG
SELECT AVG(SENSOR_VALUE) FROM PLANTS;
-- LIKE
SELECT * FROM PLANTS WHERE PLANT_NAME LIKE '%ro%';
-- ----------------------------------------------------------------------------------------------
-- Comando UPDATE para atualizar os registros dos dados
SELECT * FROM PLANTS;

UPDATE PLANTS SET SENSOR_VALUE = 90, SENSOR_LEVEL = 'HIGH' WHERE PLANT_NAME = 'Babosa';

DELETE FROM PLANTS WHERE PLANT_NAME = 'COQUEIRO';